= Première itération 

*Amine* 

Question

* Interfaces et objets pour Question et objets associés. Une question comprend un énoncé (« phrasing »), une langue, un ensemble de réponses possibles, chacune associée à l’information indiquant si cette réponse est correcte, un identifiant (int), et un auteur. Un auteur est identifié par un id (int) et a un e-mail. Utiliser un objet Person pour les auteurs. Un énoncé et une réponse sont des textes simples. L’ensemble de réponses peut être remplacé par une information « Y/N » ou « T/F » ou « free », indiquant une question oui / non, ou vrai / faux, ou de réponse libre. Créer à cet effet une interface MultipleChoiceQuestion qui étend Question. L’auteur peut associer un identifiant personnel (string) à une question. Ceci est stocké hors de l’objet Question. Cet identifiant peut changer. (La paire (auteur, identifiant) doit être unique.) Une question est immuable. (2)

*Commentaire de M.Cailloux*

Il faut créer une hiérarchie de questions qui permettra de les gérer facilement, en parallèle de l’entité elle-même. Créer une interface IQuestion, et des types concrets FreeQuestion, FMCQuestion (Multiple Choice), qui a une méthode getPropositions (remplaçant getAnswers actuelle), YesNoQuestion qui étend MCQuestion, TrueFalseQuestion qui étend MCQuestion, etc.

Il faut aussi écrire les tests unitaires.


*Remarque*

Implémentation des tests unitaires associés au fur et à mesure.

*Khaled*

* Niveau de difficulté : Introduire deux nouvelle notions QuestionPhrasing et stats, deux class QuestionPhrasing (id, phrasing) et Stats(id, CountSelect, CountCorrectAnswer), par la suite la class existante Question  contiendra (id, QuestionPhrasing, Stats, … answers, …) 

*Exemple : *
Instance de QuestionPhrasing qp1 : "combien font 2+2 ?".
Instance de Question q1 : "combien font 2+2 ?" 4 ; 6 ; 8 ; 0 ?
Instance de Question q2 : "combien font 2+2 ?" 0 ; 4 ?
(q1 et q2 contiennent chacune une référence vers qp1)
Pour un examen : 
CountSelect = nombre de candidats participants à l’examen
CountCorrectAnswer = Un compteur pour calculer le nombre de candidats qui ont donné une bonne réponse.

*Exemple :*
Pour une Question 
Exam 1 (20 participants, 10 ont donné la bonne réponse)
ParticipateCounter = 20
CountCorrectAnswer = 10
Exam 1 (30 participants, 20 ont donné la bonne réponse)
CountSelect = 20+30 = 50
CountCorrectAnswer = 10+20 = 30
Ainsi de suite.
Le ratio [CountCorrectAnswer / CountSelect ] donne le niveau de difficulté de la question (0-0,33 hard; 0,33-0,66 Medium;  0,66-1 Easy)

*Remaque*

au début les question sont toutes faciles, après un certain nombre d'utilisation, le ratio aura de plus en plus de sens avec un nombre de population important.

*Mohamed*

* Question Xml : Représentation des questions sur un schéma XML (lecture et écriture).

* Faire les différentes conversion en Xml (QuestionText). Et ajout Tests unitaires pour GetQuestion(id).

*Valentin*

* Gestion des questions : Implémentation de PersonalTags
Chaque personne peut associer un identifiant personnel à chaque question (y compris celles dont la personne n’est pas auteur). La paire (personne, identifiant) doit être unique. Chaque personne peut associer un ensemble de sujets à chaque question (exemple : Math, Java, Programmation). Ces sujets sont personnels. (Donc deux personnes peuvent indiquer des sujets différents pour une même question.) Servlets Get et Set correspondantes. (1)

*Remarque*
La création d'un servlet permettant d'exporter un examen en .pdf se fera dans la seconde itération.

*Katia*


* ServletsModify: ChangeResponseTypeTF(id orig, new author id): new id et ChangeResponseTypeYN(id orig, new author id). Change la réponse à une question en créant une nouvelle question qui a un autre type de réponse (c-à-d Y/N ou T/F) et en renvoyant son nouvel id. 

* ChangeQuestionLanguage(id orig, new author id, new language): new id ( modifier les classes existantes par rapport à ce qu’il a été demandé dans l’énoncé, récupération des paramètres soumis dans le formulaire HTML)

* Ajout de tests unitaires (Question, Person)

*Alexandre*

* Online : Faire tourner le serveur en ligne grâce au service d’IBM. (0,5)

= Deuxième itération

*Amine*

* Servlet NewQuestion(question): id, qui reçoit une question en format JSON ; servlet GetQuestion(id): question, qui envoie une question à partir de son id. (1)
* Gestion des réponses (particulièrement les réponses libres en utilisant la distance de Leveinstein) Dans la partie correction
* La relation SameAbility (ServletAbilities)

*Khaled*

* Creation examen : Implémenter un examen qui permet, avec un GUI rudimentaire ou en ligne de commande, la création d'examens (chaque examen se compose de plusieurs types de questions) pour que les candidats puissent passer les examens

*Remarque* ceci n'inclue pas la partie passage d'examen.

*Mohamed*

*Aaméliorer la création d'un PersnnelTag et l'ajout d'un servlet Set pour ce dernier. De plus, implémenter un servlet getPerson et en fin un servlet qui permet de supprimer les données dans la BD ( les questions, les personnes ... )

*Valentin*

* Les examens seront exportables en fichier .pdf vià un servlet Exportpdf. Un Examen sera le regroupement de plusieurs questions.
* Implémentation d'algorithmes spécifiques et complexes pour une meilleure gestion des examens comme le K-Means algorithm  

*Katia*

* QuestionMultiFormat: Récupérer une question à partir de son id, en format XML ou JSON. Introduire une question en multiples formats. Transformer en REST. Cookie permet de mémoriser un id person, il est utilisé si l’id person n’est pas fourni, pour les servlets qui requièrent ce paramètre.

*Remarque*

De cette fonctionnalité j’ai compris que : Un utilisateur aura la possibilité de récupérer la question dans le format qu’il souhaite (Json ou XML).  Je voudrais que vous me confirmiez svp, si c’est bien ça que vous attendez de cette fonctionnalité.

*Alexandre*

* UseDB : Modifier les servlets pour qu’ils écrivent dans et lisent la BDD. (1)
* Correction des warnings et exceptions au cours du build (0,5)
* Résolus à ce jour :
* deprecated warning : tabulation manquante pour l'attribut "services" dans le travis.yml
* warning : dépendance manquante pour glassfish.grizzly dans le pom.xml
* A corriger :
Travis indique un warning (Deprecated) lors du déploiement
SEVERE: Exception during lifecycle processing
org.glassfish.deployment.common.DeploymentException: CDI deployment failure:Exception List with 1 exceptions:
Exception 0 :
java.lang.IllegalStateException: Could not find beans for Type=class org.apache.deltaspike.core.impl.scope.window.WindowBeanHolder and qualifiers:[]


= Troisième itération

*Amine*

* Gérer la relation Improvement
* Gérer la relation asSubtleAs
* Créer les interfaces nécessaires

* Passage d'examen : Implémenter le passage d'un examen qui permet, avec avec un GUI rudimentaire ou en ligne de commande, la création des réponses aux questions par un candidat. Ceci permet  un candidat de passer un examen en ligne et garder sa copie d'examen pour une correction (évaluation) par un enseignant

*Remarque* ceci n'inclue pas la partie correction d'examen

*Khaled* 
* Passage d'examen : Implémenter le passage d'un examen qui permet, avec avec un GUI rudimentaire ou en ligne de commande, la création des réponses aux questions par un candidat. Ceci permet  un candidat de passer un examen en ligne et garder sa copie d'examen pour une correction (évaluation) par un enseignant

*Remarque*

Ceci n'inclue pas la partie correction d'examen

*Mohamed*

* Modifier Examen : changer les sujets d'exams qui seront créer par khaled. Tel que cette opération est accessible que pour les enseignants. l'enseignant peut soit changer le niveau de difficulté d'une question, changer une question... avec cookie qui mémorise id d'un enseignant(1)

*Valentin*

* Gestion de la partie Author : Intégration d'une API de Data Visualisation dans la partie Author pour obtenir des statistiques poussées et intéressantes sous forme de diagrammes, de courbes et de graphiques

*Katia*

* Question par thème: Chaque personne peut associer un thème (info, math, economie....) à chaque question (y compris celles dont la personne n’est pas auteur). Et afficher toutes les questions qui concernent un thème données

*Alexandre*

* Datavisualisation : Dashboards sur les données de la BDD. (1)

= URL du site web

https://examcollab.eu-gb.mybluemix.net/

= Les anciens collaborateurs

* Jeff Azzam

* Sid Ahmed Imloul

* Sofiath Lanignan

* Lamine Tamendjari

* Omar Yaghi

* Abdelmadjid Yous
