= Collaborative exams
:gitHubUserName: oliviercailloux
:groupId: io.github.{gitHubUserName}
:artifactId: collaborative-exams
:repository: Collaborative-exams

image:https://travis-ci.com/{gitHubUserName}/{repository}.svg?branch=master["Build Status", link="https://travis-ci.com/{gitHubUserName}/{repository}"]

A Java project developed during several sessions of the https://github.com/oliviercailloux/java-course[Java course] taught at Université Paris-Dauphine (in http://www.mido.dauphine.fr/[MIDO] M2 MIAGE).

The code is hereby published under the MIT License, with the permission of the contributors.

* Jeff Azzam
* Sid Ahmed Imloul
* Sofiath Lanignan
* Lamine Tamendjari
* Omar Yaghi
* Abdelmadjid Yous

== Published at
http://collaborative-exams.eu-gb.mybluemix.net/

== TODO
Il faut créer une hiérarchie de questions qui permettra de les gérer facilement, en parallèle de l’entité elle-même. Créer une interface IQuestion, et des types concrets FreeQuestion, FMCQuestion (Multiple Choice), qui a une méthode getPropositions (remplaçant getAnswers actuelle), YesNoQuestion qui étend MCQuestion, TrueFalseQuestion qui étend MCQuestion, etc.

=== Propositions de fonctionnalités à corriger ou créer pour le groupe suivant

* De manière générale, assurer que l'intégralité du projet fonctionne EN LIGNE car le but est de réaliser une application en ligne.
Pour que chaque membre du groupe puisse tester le code de sa branche, il peut déployer sa branche sur IBM Cloud à un URL différent de l'URL des autres membres du groupe.
Le document "Tutoriel - Déployer votre branche du projet sur votre compte IBM Cloud.pdf" disponible sur la branche master peut vous aider pour cela.

* Corriger l’Exception au cours du build décrite ci-dessous :
SEVERE: Exception during lifecycle processing org.glassfish.deployment.common.DeploymentException: CDI deployment failure:Exception List with 1 exceptions: Exception 0 : java.lang.IllegalStateException: Could not find beans for Type=class org.apache.deltaspike.core.impl.scope.window.WindowBeanHolder and qualifiers:[] https://stackoverflow.com/questions/55114271/travis-ci-deployment-of-a-jax-rs-application-fails-without-any-error https://travis-ci.community/t/deployment-of-a-jax-rs-application-fails-without-any-error/2622 Recherches diverses (voir mon pull request "alex iteration 2")

* Connecter l'application au service Db2 (BDD SQL) d'IBM Cloud

* Pour le bouton "Add question manually" de la page questions.html
Javascript pour convertir enun objet JSON les informations d’ajout de question saisies à la main dans le formulaire et pouvoir ainsi utiliser le servlet NewQuestionJson.java qui prend en entrée un fichier JSON pour créer une question et l'ajouter à la BDD.

* Assurer que chaque bouton du site appelle bien un formulaire et que ce formulaire soit effectif vis-à-vis de la BDD.

* Pour la page questions.html :
Afficher dynamiquement dans le tableau les nuplets de questions enregistrés dans la BDD.

* Pour la page exams.html :
Afficher dynamiquement dans le tableau les nuplets de d'exams enregistrés dans la BDD.

* Pour la page authors.html :
Afficher dynamiquement dans le tableau les nuplets d'authors enregistrés dans la BDD.

* Pour la page questions.html :
Pouvoir modifier et supprimer les nuplets de questions enregistrés dans la BDD à partir des boutons du tableau.

* Pour la page exams.html :
Pouvoir modifier et supprimer les nuplets d'exams enregistrés dans la BDD à partir des boutons du tableau.

* Pour la page authors.html :
Pouvoir modifier et supprimer les nuplets d'authors enregistrés dans la BDD à partir des boutons du tableau.

* Pour la page index.html :
Afficher dynamiquement le calcul des données agrégées de la BDD pour les afficher dans les dashboards.
Par exemple, le nombre de questions de type True/False créées.

